CREATE DATABASE IF NOT EXISTS {{DATABASE}};

CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{RAW_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{STAGING_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{INTERMEDIATE_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{MARTS_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{AUDIT_SCHEMA}};
