CREATE FILE FORMAT IF NOT EXISTS {{DATABASE}}.{{RAW_SCHEMA}}.{{FILE_FORMAT}}
    TYPE = CSV
    COMPRESSION = AUTO
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    REPLACE_INVALID_CHARACTERS = FALSE
    SKIP_BYTE_ORDER_MARK = TRUE
    ENCODING = 'UTF8';

CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{RAW_SCHEMA}}.{{STAGE}}
    URL = {{S3_URL}}
    STORAGE_INTEGRATION = {{STORAGE_INTEGRATION}}
    FILE_FORMAT = (FORMAT_NAME = {{FILE_FORMAT_FQN_LITERAL}})
    COMMENT = 'Immutable Olist ingestion batches; manifests are commit markers';
